Controllers/ExpensesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using BabzRent.Data;
using BabzRent.Models.Expenses;
using BabzRent.ViewModels.ExpensesViewModels;
using Org.BouncyCastle.Asn1.Cms.Ecc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Razor.Language.Intermediate;
using BabzRent.Models.Properties;

namespace BabzRent.Controllers
{
    public class ExpensesController : Controller
    {
        private ApplicationDbContext _context { get; set; }

        public ExpensesController(ApplicationDbContext context)
        {
            _context = context;
        }
        // GET: Expense
        public ActionResult Index()
        {
            var viewModel = new ExpenseViewModel()
            {
                Expenses = _context.Expenses.Include(e => e.Company).Include(e => e.ExpenseLocation).Include(e => e.BillableProperty).Include(e => e.BillableLocation).ToList()
            };

            return View(viewModel);
        }

        public ActionResult NewExpense()
        {
            var viewModel = new ExpenseFormViewModel
            {
                Expense = new Expense(),
                Companies = _context.ExpenseCompanies.ToList(),
                Locations = ExpenseCompanyLocation.GetLocationsSelectList(),
                BillableLocations = _context.PropertyLocations.ToList(),
                BillableProperties = Property.GetPropertySelectList()
            };
            return View("ExpenseForm", viewModel);
        }

        public ActionResult SaveExpense(Expense expense)
        {
            var expenseRepo = new Expense(_context);
            expenseRepo.SaveExpense(expense);

            return RedirectToAction("Index");
        }



        public ActionResult GetCompanyLocations(int companyId)
        {// Used to return a JSON formatted object
            if (companyId != 0)
            {
                var locationRepo = new ExpenseCompanyLocation(_context);
                IEnumerable<SelectListItem> locations = locationRepo.GetLocationsSelectList(companyId);
                return Ok(locations);
            }
            return null;
        }

        public ActionResult GetBillableProperties(int locationId)
        {
            if (locationId != 0)
            {
                var propertyRepo = new Property(_context);
                IEnumerable<SelectListItem> properties = propertyRepo.GetPropertySelectList(locationId);
                return Ok(properties);
            }

            return null;
        }
        


        public ActionResult NewCompany()
        {
            var company = new CompanyFormViewModel()
            {
                Company = new ExpenseCompany(),
                CompanyLocation = new ExpenseCompanyLocation()
            };
            return View("CompanyForm", company);
        }

        public ActionResult SaveCompany(CompanyFormViewModel viewModel)
        {
            var expenseCompanyRepo = new ExpenseCompany(_context);
            expenseCompanyRepo.SaveCompany(viewModel);

            return View("Index");
        }

        public ActionResult EditCompany(int companyId)
        {
            var company = new CompanyFormViewModel()
            {
                Company = _context.ExpenseCompanies.SingleOrDefault(c => c.Id == companyId)
            };
            return View("CompanyForm", company);
        }



        public ActionResult NewCompanyLocation()
        {
            var viewModel = new CompanyLocationViewModel()
            {
                CompanyLocation = new ExpenseCompanyLocation(),
                Companies = _context.ExpenseCompanies.ToList()
            };

            return View("CompanyLocationForm", viewModel);
        }

        public ActionResult SaveCompanyLocation(CompanyLocationViewModel viewModel)
        {
            if(viewModel.CompanyLocation.Id == 0)
            {
                _context.ExpenseCompanyLocations.Add(viewModel.CompanyLocation);
            }
            else
            {
                var locationInDb = _context.ExpenseCompanyLocations.Single(l => l.Id == viewModel.CompanyLocation.Id);
                locationInDb.CompanyId = viewModel.CompanyLocation.CompanyId;
                locationInDb.Address1 = viewModel.CompanyLocation.Address1;
                locationInDb.Address2 = viewModel.CompanyLocation.Address2;
                locationInDb.Address3 = viewModel.CompanyLocation.Address3;
                locationInDb.City = viewModel.CompanyLocation.City;
                locationInDb.PostCode = viewModel.CompanyLocation.PostCode;
                locationInDb.County = viewModel.CompanyLocation.County;
                locationInDb.Country = viewModel.CompanyLocation.Country;
            }
            _context.SaveChanges();
            return View("Index");
        }

        public ActionResult Companies()
        {
            var viewModel = new CompaniesViewModel()
            {
                Companies = _context.ExpenseCompanies.ToList(),
                Locations = _context.ExpenseCompanyLocations.ToList()
            };

            return View(viewModel);

        }
    }
}

Controllers/ReportsController.cs
using BabzRent.Models;
using BabzRent.Models.Billing;
using BabzRent.Models.Reports;
using BabzRent.ViewModels.ReportsViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using BabzRent.Data;
using BabzRent.Models.Tenancies;
using BabzRent.Models.Expenses;
using Microsoft.CodeAnalysis;

namespace BabzRent.Controllers
{
    public class ReportsController : Controller
    {
        public ApplicationDbContext _context { get; set; }

        public ReportsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Reports
        public ActionResult Index()
        {
            return View(); 
        }

        public ActionResult KPIRYearForm()
        {
            List<int> dates = new List<int>();

            for (int i = 0; i < 6; i++)
            {
                dates.Add(DateTime.Now.Year - i);
            };

            var viewModel = new KPIRYearFormViewModel
            {
                Locations = _context.PropertyLocations.ToList(),
                Dates = dates
            };

            return View(viewModel);
        }

        public ActionResult KPIRYearlyView(int locationId, int? financialYear)
        {
            IEnumerable<Invoice> invoices;
            IEnumerable<Expense> expenses;
            var invoice = new Invoice(_context);
            var expense = new Expense(_context);

            if (financialYear != null)
            {
                invoices = invoice.GetAllInvoicesAtLocationForTaxYear(locationId, (int)financialYear);
                expenses = expense.GetAllExpensesAtLocationForTaxYear(locationId, (int)financialYear);
            }
            else
            {
                invoices = invoice.GetAllInvoicesAtLocation(locationId);
                expenses = expense.GetAllExpensesAtLocation(locationId);
            }

            var viewModel = new KPIRViewModel()
            {
                KPIRs = KPIR.ExpenseAndInvoicesToKPIR(invoices, expenses),
                Tenancies = TenancyNames.Get(_context.Tenancies.Include(m => m.Property).ToList()),
            };
            ViewBag.ReportingYear = financialYear;
            ViewBag.Location = _context.PropertyLocations.Single(l => l.Id == locationId).ShortCode;
            return View(viewModel);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BabzRent</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <partial name="_NavBar" />
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BabzRent - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_NavBar.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BabzRent</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
            <partial name="_LoginPartial" />
            <partial name="_NavBar1" />
        </div>
    </div>
</nav>

Views/Shared/_NavBar1.cshtml
<ul class="navbar-nav flex-grow-1">
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Tenants" asp-action="Index">Tenants</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Property" asp-action="Index">Properties</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Tenancy" asp-action="Index">Tenancy</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Contract" asp-action="Index">Contract</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Maintenance" asp-action="Index">Maintenance</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Billing" asp-action="Index">Billing</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Expenses" asp-action="Index">Expenses</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Reports" asp-action="Index">Reports</a>
    </li>
</ul>

Views/Shared/_NavBarMaintenance.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("BabzRent", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Maintenance", "Index", "Maintenance")</li>
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>